#ifndef __MACROSMY__H___
#define __MACROSMY__H___

typedef enum
{
	//*LAYOUTS*//
	L_MAINMENU,
	L_PLAYSINGLE,
	L_PLAYMULTI,
	L_OPTIONS,
	L_FREERUN,
	//*BUTTONS*//
	//main//
	B_PLAYSINGLE,
	B_PLAYMULTI,
	B_BACK,
	//single//
	B_CARRER,
	B_ELIMINATION,
	B_ENDLESS_RUN,
	B_FREERUN,
	//frerrunsingle//
	B_AMOUNTOFOPPONENTSSLIDER,
	B_DIFFICULTYSLIDER,
	B_DIFFICULTYLABELSLIDER,
	B_FREERUNACCEPTANDPLAY,
	BACK,
};
#endif