#ifndef __MACROSMY__H___
#define __MACROSMY__H___

typedef enum
{
	//*LAYOUTS*//	//*BUTTONS*//
	L_MAINMENU, B_PLAYSINGLE, B_PLAYMULTI, B_OPTIONS, B_BACK,
		L_PLAYSINGLE,LAB_SINGLEPLAYER, B_CARRER, B_FREERUN,
			L_CARRER, LAB_CARRER,
			L_FREERUN, LAB_FREERUN, LAB_CHOOSEMODE, PG_CHOOSEMODE, B_AMOUNTOFOPPONENTSSLIDE, B_DIFFICULTYSLIDER, LAB_OPPONENTSNUMBERSLIDER, B_FREERUNACCEPTANDPLAY, LAB_DIFFICULTYLABEL,
		L_PLAYMULTI,
			L_MULTIFREELOCALRUN,LAB_FREERUNMULTI,LAB_OPPONENTSNUMBERMULTI,CH_MULTICOLLECTOR,CH_MULTIGATE,CH_MULTIELIM,LAB_PLAYERSNUMBER,
		L_OPTIONS
};
#endif